name: ahsan
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  svg_flutter: ^0.0.1
  url_launcher: ^6.0.9
  mobile_scanner: ^3.5.0
  webview_flutter: ^2.0.14
  geolocator: ^10.1.0
  geocoding: ^2.1.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/
    - assets/doa/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Bold.ttf
        - asset: assets/font/Poppins-Medium.ttf
        - asset: assets/font/Poppins-Regular.ttf

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/image/app-logo.png"
    remove_alpha_ios: true
